package com.art.shooter.ui;
import com.art.shooter.utils.Resources;
import com.badlogic.gdx.graphics.Color;
import com.badlogic.gdx.scenes.scene2d.utils.Drawable;
public enum Squircle {
    //enums are generated by gradle task "generateSquircles", don't modify
    // BEGIN-ENUM-CONSTANTS
    SQUIRCLE_15(15),
    SQUIRCLE_20(20),
    SQUIRCLE_25(25),
    SQUIRCLE_35(35),
    SQUIRCLE_40(40),
    SQUIRCLE_50(50),
;
    // END-ENUM-CONSTANTS
    private int radius;
    Squircle(int radius) {
        this.radius = radius;
    }

    public Drawable getDrawable() {
        return Resources.obtainDrawable("ui/squircles/squircle-" + radius);
    }

    public Drawable getDrawable (Color color) {
        String path = "squircles/squircle-" + radius;
        return Resources.obtainDrawable(path, color);
    }


}